# Generated by Django 4.2.3 on 2023-10-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='receipt',
            field=models.ImageField(blank=True, default='/images/receipts/placeholder.png', null=True, upload_to='images/receipts'),
        ),
    ]
