# Generated by Django 4.2.3 on 2023-10-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shippingaddress_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='receipt',
            field=models.ImageField(default='/images/receipts/placeholder.png', upload_to='images/receipts'),
        ),
    ]
