# Generated by Django 4.2.3 on 2023-10-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_shippingaddress_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='receipt',
            field=models.ImageField(default='/receipts/placeholder.png', upload_to='receipts'),
        ),
    ]
