# Generated by Django 4.2.3 on 2023-10-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_shippingaddress_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='receipt',
            field=models.ImageField(upload_to='receipts'),
        ),
    ]
