# Generated by Django 4.2.3 on 2023-10-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_shippingaddress_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Preparing for Dispatch', 'Preparing for Dispatch'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected')], default='Pending', max_length=200),
        ),
    ]
